### ISSUE TITLE
Got exception while decode gvas save file.

### ISSUE THREAD

**Issue by Derfirm** [IncredulousMonk/sod2-tools#1]
Hello, sir!
Thx for tools, its look like impressive, but I got some error, while trying  to decode some savefile

`erl`  cmd got output

```erl
Erlang/OTP 24 [erts-12.2.1] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [dtrace]

Eshell V12.2.1
```
decode got error
```bash
./decomp FOsME_E_MainSave.sav save.0

escript: exception error: bad argument
  in function  binary_part/3
     called as binary_part(<<71,86,65,83,2,0,0,0,10,2,0,0,4,0,26,0,2,0,250,186,
                             243,0,19,0,0,0,43,43,85,69,52,43,82,101,108,101,
                             97,115,101,45,52,46,50,54,0,3,0,0,...>>,
                           1835092904,8)
     *** argument 2: out of range
  in call from decomp__escript__1643__879497__19834__8:extract_property_block_details/1 (./decomp, line 76)
  in call from decomp__escript__1643__879497__19834__8:decompress/2 (./decomp, line 42)
  in call from escript:run/2 (escript.erl, line 750)
  in call from escript:start/1 (escript.erl, line 277)
  in call from init:start_em/1
  in call from init:do_boot/3
  ```

**Comment by IncredulousMonk** [comment]
Hello.  Thanks for the bug report.

It looks like my code is failing where it tries to extract the block sizes from the file header.

What game is the save file from?  At the moment my code works only for State of Decay 2 save files.

**Comment by Derfirm** [comment]
Bad news, do I have a chance to see extended version of editor for most UE games?
Example file
[FOsME_E_MainSave.sav.zip](https://github.com/IncredulousMonk/sod2-tools/files/8002870/FOsME_E_MainSave.sav.zip)

**Comment by IncredulousMonk** [comment]
Sorry, I don't intend to create a generic tool for all UE games, because that's a lot more work than I'm willing to commit.  I'm really only interested in State of Decay 2 at the moment.

I'm going to close this issue, but if I ever decide to extend the scope then I'll consider reopening it.
